# Generated by Django 4.2.7 on 2023-11-26 22:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id_comida', models.AutoField(primary_key=True, serialize=False)),
                ('nome_comida', models.CharField(max_length=200)),
                ('preco', models.FloatField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Motoboy',
            fields=[
                ('placa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_motoboy', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('cnpj', models.AutoField(primary_key=True, serialize=False)),
                ('nome_restaurante', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trabalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_contratacao', models.DateField(default=datetime.datetime(2023, 11, 26, 22, 54, 17, 390772, tzinfo=datetime.timezone.utc))),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.motoboy')),
                ('restaurante', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurante')),
            ],
        ),
        migrations.AddField(
            model_name='restaurante',
            name='motoboys',
            field=models.ManyToManyField(through='delivery.Trabalha', to='delivery.motoboy'),
        ),
        migrations.CreateModel(
            name='Pedir',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.cliente')),
                ('comidas', models.ManyToManyField(to='delivery.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pedido', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='delivery.pedir')),
                ('motoboy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.motoboy')),
            ],
        ),
        migrations.AddField(
            model_name='comida',
            name='restaurante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comidas', to='delivery.restaurante'),
        ),
    ]
