# Generated by Django 3.2.23 on 2023-11-25 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.AutoField(primary_key=True, serialize=False)),
                ('nomecliente', models.CharField(max_length=200)),
                ('endereco', models.FloatField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('nomecomida', models.CharField(max_length=200)),
                ('preco', models.FloatField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Motoboy',
            fields=[
                ('placa', models.AutoField(primary_key=True, serialize=False)),
                ('nomemotoboy', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('cnpj', models.AutoField(primary_key=True, serialize=False)),
                ('nomerestaurante', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trabalha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurante')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.motoboy')),
            ],
        ),
        migrations.CreateModel(
            name='Pedir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.cliente')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.comida')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.comida')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.motoboy')),
            ],
        ),
        migrations.CreateModel(
            name='Comprar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurante')),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.cliente')),
            ],
        ),
    ]
