# Generated by Django 3.2.23 on 2023-11-26 21:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedir',
            name='comida',
        ),
        migrations.AddField(
            model_name='pedir',
            name='comidas',
            field=models.ManyToManyField(to='delivery.Comida'),
        ),
        migrations.AddField(
            model_name='pedir',
            name='motoboy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='delivery.motoboy'),
        ),
        migrations.AlterField(
            model_name='trabalha',
            name='data_contratacao',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 21, 36, 34, 908624, tzinfo=utc)),
        ),
    ]
