# Generated by Django 3.2.23 on 2023-11-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='cnpj',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurante'),
        ),
    ]
