# Generated by Django 3.2.23 on 2023-11-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalha',
            name='restaurante',
        ),
        migrations.AddField(
            model_name='trabalha',
            name='restaurante',
            field=models.ManyToManyField(to='delivery.Restaurante'),
        ),
    ]
