# Generated by Django 3.2.23 on 2023-12-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurante',
            name='motoboys',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default=0, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Trabalha',
        ),
    ]
