# Generated by Django 3.2.23 on 2023-12-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20231203_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='cnpj',
            field=models.CharField(default='00.000.000/0001-00', max_length=18),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
