# Generated by Django 3.2.23 on 2023-11-26 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_auto_20231126_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedir',
            name='motoboy',
        ),
        migrations.AlterField(
            model_name='trabalha',
            name='data_contratacao',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 21, 36, 56, 811279, tzinfo=utc)),
        ),
    ]
