# Generated by Django 3.2.23 on 2023-11-26 22:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_auto_20231126_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedir',
            name='id_pedido',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabalha',
            name='data_contratacao',
            field=models.DateField(default=datetime.datetime(2023, 11, 26, 22, 17, 2, 420258, tzinfo=utc)),
        ),
    ]
